web_macro_mech/models.py
from sqlalchemy import String, Text, Boolean, ForeignKey
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from flask_login import UserMixin


class Base(DeclarativeBase):
    pass


class User(Base, UserMixin):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(150), unique=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String(128), nullable=False)
    #
    problems: Mapped[list["Problem"]] = relationship(back_populates="user")


class Problem(Base):
    __tablename__ = "problems"

    id: Mapped[int] = mapped_column(primary_key=True)
    title: Mapped[str] = mapped_column(String(150), nullable=False)
    cond: Mapped[str] = mapped_column(Text, nullable=False)
    init: Mapped[str] = mapped_column(Text, nullable=False)
    answer: Mapped[str] = mapped_column(Text, nullable=False)
    isOpen: Mapped[bool] = mapped_column(Boolean, default=True)
    #
    username: Mapped[str] = mapped_column(ForeignKey("users.username"))
    user: Mapped["User"] = relationship(back_populates="problems")
    

web_macro_mech/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
import os

from .models import Base, User


bcrypt = Bcrypt()

# БД має знаходитися в кореневому каталозі пакета
db_path = os.path.join(os.path.dirname(__file__), "webmacromech.db")
print("DB path: " + db_path)
engine = create_engine(f"sqlite:///{db_path}", echo=False)

SessionLocal = sessionmaker(bind=engine, expire_on_commit=False)

login_manager = LoginManager()


def create_app():
    app = Flask(__name__)
    app.secret_key = 'very-secret-key'  # Для сесій

    bcrypt.init_app(app)
    login_manager.init_app(app)

    Base.metadata.create_all(engine)

    from .routes import main_bp, auth_bp

    app.register_blueprint(main_bp)
    app.register_blueprint(auth_bp)

    login_manager.login_view = 'auth.login'  # якщо не авторизований — редірект

    return app


@login_manager.user_loader
def load_user(user_id):
    with SessionLocal() as session:
        return session.get(User, int(user_id))

web_macro_mech/routes/__init__.py
from .main import main_bp
from .auth import auth_bp

web_macro_mech/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user

from sqlalchemy import select
from sqlalchemy.orm import Session
from urllib.parse import unquote


from ..models import Problem, User
    
from .. import SessionLocal, bcrypt

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():

    message = error = None

    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        with SessionLocal() as db:
            user_exists = db.scalar(select(User).where(User.username == username))
            if user_exists:
                error = 'Користувач вже існує'
            else:
                password_hash = bcrypt.generate_password_hash(password).decode('utf-8')
                new_user = User(username=username, password_hash=password_hash)
                db.add(new_user)
                db.commit()
                message = 'Користувача зареєстровано успішно'

    return render_template('register.html', message=message, error=error)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():

    error = None
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        with SessionLocal() as db:
            user = db.scalar(select(User).where(User.username == username))
            if user and bcrypt.check_password_hash(user.password_hash, password):
                login_user(user)
                return redirect(url_for('main.index'))
            else:
                error = 'Невірне імʼя користувача або пароль'

    return render_template('login.html', error=error)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

web_macro_mech/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user

from urllib.parse import unquote

from ..models import Problem
from .. import SessionLocal

main_bp = Blueprint("main", __name__)

# HOME PAGE
#
@main_bp.route('/', methods=['GET'])
# @login_required
def index():
    nameInHeader = ''
    if current_user.is_authenticated:
        nameInHeader = ' - ' + current_user.username
    return render_template('index.html', nameInHeader = nameInHeader)


#  API - список задач
#
@main_bp.route('/opened_probs', methods=['GET'])
@main_bp.route('/my_probs', methods=['GET'])
def probs():
    s = ''
    with SessionLocal() as db:
        if request.path == '/opened_probs': 
           problems = db.query(Problem).filter(Problem.isOpen == True).all()
        elif request.path == '/my_probs':
           problems = db.query(Problem).filter(Problem.username == current_user.username).all()

    for p in problems:
        s += f"""TITLE: {p.title}
COND: {p.cond}
INIT: {p.init}
ANSWER: {p.answer}
---
"""
    
    if len(s) > 0:
        s = "TITLE: Clear Scene\nCOND:\nINIT:\nANSWER:\n---\n" + s
    else:
        # load from ststic file
        with open('problems.txt', 'r') as f:
            s = f.read()
    return s


#  Запит на головну адмін форму 
#
@main_bp.route('/admin', methods=['GET'])
@login_required
def admin():
    with SessionLocal() as db:
        problems = db.query(Problem).filter(Problem.username == current_user.username).all()
        return render_template('admin.html', problems=problems)


# Відкриття-закриття задач з головної форми
#
@main_bp.route('/switch/<id>', methods=['GET'])
@login_required
def switch(id):
    with SessionLocal() as db:
        problem = db.get(Problem, id) 
        problem.isOpen = not problem.isOpen
        db.commit()    
        problems = db.query(Problem).filter(Problem.username == current_user.username).all()
    return render_template('admin.html', problems=problems)




#  Запит на форму додавання задачі
#
@main_bp.route('/add_prob/<scene>', methods=['GET'])
@main_bp.route('/add_prob/<scene>', defaults={'scene': None}, methods=['POST'])
@login_required
def add_prob(scene):
    if request.method == 'GET':
        scene = unquote(scene) if scene else None
        return render_template('add_prob.html', init=scene) 
       
    elif request.method == 'POST':
        problem = Problem()
        problem.title = request.form.get('title')
        problem.cond = request.form.get('cond')
        problem.init = request.form.get('init')
        problem.answer = request.form.get('answer')
        problem.username = current_user.username
        problem.isOpen = False
        
        with SessionLocal() as db:
            db.add(problem)
            db.commit()
        return redirect(url_for('main.admin'))        


#  Запит на форму редагування задачі
#
@main_bp.route('/edit_prob/<id>', methods=['GET','POST'])
@login_required
def edit_prob(id):
    if request.method == 'GET':        
        with SessionLocal() as db:
            problem = db.get(Problem, id) 
        return render_template('edit_prob.html', problem = problem);
     
    elif request.method == 'POST':
        with SessionLocal() as db:           
            problem = db.get(Problem, id) 

            problem.cond = request.form.get('cond')
            problem.init = request.form.get('init')
            problem.answer = request.form.get('answer')
            problem.isOpen = request.form.get('isOpen') == 'True'
            db.commit()
        return redirect(url_for('main.admin'))        


#  Запит на форму видалення задачі
#
@main_bp.route('/del_prob/<id>', methods=['GET','POST'])
@login_required
def del_prob(id):
    if request.method == 'GET':
        with SessionLocal() as db:
            problem = db.get(Problem, id) 
        return render_template('del_prob.html', problem = problem);
     
    elif request.method == 'POST':
        with SessionLocal() as db:
            problem = db.get(Problem, id) 
            db.delete(problem)
            db.commit()
        return redirect(url_for('main.index'))        

templates/add_prob.html
{% extends "layout.html" %}

{% block title %} AddProb {% endblock %}

{% block content %}
    <h2>Додавання Задачі</h2>
    <form method="POST" >
        <input type="text" name="title" placeholder="Назва" value="{{title}}" required>
        <textarea rows="5" name="cond" title="Умова" required>{{cond}}</textarea>
        <textarea rows="10" name="init" title="Сцена" required>{{init}}</textarea>
        <input type="text" name="answer" placeholder="Відповідь"value="{{answer}}" required>
        
        <button type="submit">Додати</button>
    </form>
{% endblock %}

templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./favicon.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="static/templates.css" />
    <title>Problems List</title>
</head>

<body class="body-admin">
    <div class="container">
        <h1 class="mt-4 user-task-page-text">Задачі користувача <i>{{current_user.username}}</i></h1>
        <div class="link-buttons">
            <a href="{{ url_for('main.add_prob') }}" class="btn btn-primary style-button-link">Додати Задачу</a>
            <a href="{{ url_for('main.index') }}" class="btn btn-primary style-button-link">На Головну</a>
            <a href="{{ url_for('auth.logout') }}" class="btn btn-primary style-button-link">Вихід</a>

        </div>

        <table class="table table-striped mt-3 style-table-user-task">
            <thead>
                <tr>
                    <th>Назва</th>
                    <th>Умова</th>
                    <th>Відкр</th>  
                    <th>Редаг</th>  
                    <th>Видал</th>                    
                </tr>
            </thead>
            <tbody>
                {% for problem in problems %}                
                <tr>
                    <td>{{ problem.title }}</td>
                    <td>{{ problem.cond }}</td>
                    {% set color = 'green' if problem.isOpen else 'red'  %}
                    {% set yesNo = 'Так' if problem.isOpen else 'Ні'  %}
                    

                    <td>
                        <a href="{{ url_for('main.switch', id=problem.id ) }}"
                           style="color: {{ color }}">{{yesNo}}</a>
                    </td>

                    <td><a class="link-del-edit" href="{{ url_for('main.edit_prob', id=problem.id ) }}">ред</a></td>
                    <td><a class="link-del-edit" href="{{ url_for('main.del_prob', id=problem.id ) }}">вид</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>

templates/del_prob.html
{% extends "layout.html" %}

{% block title %} DelProb {% endblock %}

{% block content %}
    <h2>Видалення задачі "{{problem.title}}"</h2>
    <form method="POST">
        <div name="cond" style="font-size: 18px; padding: 0px 10px 20px 10px;">{{problem.cond}}</div>
        <button type="submit">Видалити</button>
    </form>
{% endblock %}

templates/edit_prob.html
{% extends "layout.html" %}

{% block title %} EditProb {% endblock %}

{% block content %}
    <h2>Редагування Задачі "{{problem.title}}"</h2>
    <form method="POST">
        <textarea rows="5" name="cond" title="Умова" required>{{problem.cond}}</textarea>
        <textarea rows="10" name="init" title="Сцена" required>{{problem.init}}</textarea>
        <input type="text" name="answer" title="Відповідь"value="{{problem.answer}}"  required>
        <input type="text" name="isOpen" title="Відкритість"value="{{problem.isOpen}}"  required>
        
        <button type="submit">Зберегти</button>
    </form>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
  <link rel="icon" href="./favicon.png" type="image/x-icon">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>

  <link rel="stylesheet" href="static/index.css" />
</head>

<body>
  <div class="container">
    
    <h3 id="header" class="head">      
      Macromechanics {{nameInHeader}}
      <button id="adminButton" class="btn btn-outline-info" title="Alt - додавання задачи"> 
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492M5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0"/>
            <path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115z"/>
          </svg>
      </button>
    </h3>

    <!---------------------- top panel (buttons row) ---------------------->

    <div class="topPanel">
      <button id="createModeButton" btn-primary class="btn btn-light" title="Balls | Lines | Links">
        Ball
      </button>
      
      <button id="modeButton" class="btn btn-sm panel-button" title="Start | Stop">
        <img src="static/assets/icons/play-fill.svg" width="20" height="20">
      </button>

      <button id="restartButton" class="btn btn-sm panel-button" title="Return to the last stop">
        <img src="static/assets/icons/skip-start.svg" width="20" height="20">
      </button>

      <button id="prettyButton" class="btn btn-sm panel-button" title="Pretty | Draft">
        <img src="static/assets/icons/circle.svg" width="16" height="16">
      </button>

      <button id="traceModeButton" class="btn btn-sm panel-button" title="Show | Hide tracks">
        N
      </button>

      <button id="helpButton" class="btn btn-sm panel-button" title="Keys:
      B - balls
      L - lines
      K - links
      C - copy ball
      F - fixed ball
      S - step
      T - tracks show/hide
      Del - delete selected">
      <img src="static/assets/icons/info.svg" width="20" height="20">
      </button>
      
      <select class="form-select-sm" id="sceneSelect" title="Select problem"></select>

      <span id="infoSpan"></span>

      <span id="mousePosSpan"></span>

      <!---------------------- top panel (sliders row) ---------------------->

      <div id="rangesDiv" style="margin: 10px 0px 0px 0px ;">
        <input type="range" id="graviRange" class="form-range" step="0.001" min="0" max="0.01" 
          title="прискорення тяжіння" />
        <label id="graviValue" class="form-label" for="graviRange"></label>

        <input type="range" id="waistRange" class="form-range" step="0.01" min="0" max="1" 
          title="Втрати від стикання (0-нема втрат)" />
        <label id="waistValue" class="form-label" for="waistRange"></label>

        <input type="range" id="waistLinkRange" class="form-range" step="0.01" min="0" max="1"
          title="Втрати від деформації перемичок (0-нема втрат)" />
        <label id="waistLinkValue" class="form-label" for="waistLinkRange"></label>

        <input type="range" id="waistFrictRange" class="form-range" step="0.001" min="0" max="2" 
          title="В'язкість повітря (0-немає в'язкості)" />
        <label id="waistFrictValue" class="form-label" for="waistFrictRange"></label>

        <input type="range" id="rigidRange" class="form-range" step="1" min="0" max="10" value="7"
            title="Модуль пружності" />
          <label id="rigidValue" class="form-label" for="rigidRange"></label>
      </div>

    </div>

    <!----------------------------- Canvas Containeer --------------------------------->
    
    <div class="canvas-cont">

      <div id="problemBoard" class="canvas-item" style="right: unset; left: 0">
        <span style="position: absolute; right: 0; color: #4335a7">&lt;&gt;</span>
        <div id="condDiv" style="color: rgb(0 0 0 / 75%);"></div>
        <input id="answerText"  placeholder="Answer" autocomplete="off">
        <button id="answerButton" class="board-button">Check</button>
      </div>

      <div id="ballBoard" class="canvas-item" style="right: 0; left: unset">
        <span style="position: absolute; color: #4335a7">&lt;&gt;</span>
        <div>
          <span class="board-label">X</span> <input id="xText" class="board-text" autocomplete="off"/>
          <span class="board-label">Y </span> <input id="yText" class="board-text" autocomplete="off"/>
        </div>
        <div>
          <span class="board-label">Vx </span> <input id="vxText" class="board-text" autocomplete="off"/>
          <span class="board-label">Vy </span> <input id="vyText" class="board-text" autocomplete="off"/>
        </div>        <div>
          <span class="board-label">Massa </span> <input id="massaText" class="board-text" autocomplete="off"/>
          <span class="board-label">Radius </span> <input id="radiusText" class="board-text" autocomplete="off"/>
        </div>
        <div>
          <span class="board-label">Color </span> 
             <select id="colorText" class="board-text">
              <option value="red">Red</option>
              <option value="blue">Blue</option>
              <option value="green">Green</option>
              <option value="gold">Gold</option>
             </select>
          <span class="board-label"> </span> <button id="applyBallButton" class="board-button">Apply</button>
        </div>
      </div>

      <div id="lineBoard" class="canvas-item" style="right: 0; left: unset">
        <span style="position: absolute; color: #4335a7">&lt;&gt;</span>
        <div>
          <span class="board-label">X1 </span> <input id="x1Text" class="board-text" autocomplete="off" />
          <span class="board-label">Y1 </span> <input id="y1Text" class="board-text" autocomplete="off" />
        </div>
        <div>
          <span class="board-label">X2 </span> <input id="x2Text" class="board-text" autocomplete="off" />
          <span class="board-label">Y2 </span> <input id="y2Text" class="board-text" autocomplete="off" />
        </div>
        <div>
          <button id="applyLineButton" class="board-button" style="float: right;">Apply</button>
        </div>
      </div>
      
      <canvas id="canvas2" width="800" height="600" class="canvas-item"></canvas>
      <canvas id="canvas" width="800" height="600" class="canvas-item"></canvas>
   
    </div>

    <!------------------ bottom panel ---------------->
    <div class="bottom-panel">

      <button id="saveSceneButton" class="btn btn-sm btn-primary scene-btn" title="Export scene">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-down-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M8.636 12.5a.5.5 0 0 1-.5.5H1.5A1.5 1.5 0 0 1 0 11.5v-10A1.5 1.5 0 0 1 1.5 0h10A1.5 1.5 0 0 1 13 1.5v6.636a.5.5 0 0 1-1 0V1.5a.5.5 0 0 0-.5-.5h-10a.5.5 0 0 0-.5.5v10a.5.5 0 0 0 .5.5h6.636a.5.5 0 0 1 .5.5"/>
          <path fill-rule="evenodd" d="M16 15.5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1 0-1h3.793L6.146 6.854a.5.5 0 1 1 .708-.708L15 14.293V10.5a.5.5 0 0 1 1 0z"/>
        </svg>
      </button>

      <textarea id="savedSceneArea" rows="1"></textarea>

      <button id="loadSceneButton" class="zzz btn btn-sm btn-primary scene-btn" title="Import scene">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-in-up-right" viewBox="0 0 16 16">
          <path fill-rule="evenodd" d="M6.364 13.5a.5.5 0 0 0 .5.5H13.5a1.5 1.5 0 0 0 1.5-1.5v-10A1.5 1.5 0 0 0 13.5 1h-10A1.5 1.5 0 0 0 2 2.5v6.636a.5.5 0 1 0 1 0V2.5a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v10a.5.5 0 0 1-.5.5H6.864a.5.5 0 0 0-.5.5"/>
          <path fill-rule="evenodd" d="M11 5.5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793l-8.147 8.146a.5.5 0 0 0 .708.708L10 6.707V10.5a.5.5 0 0 0 1 0z"/>
        </svg>
      </button>

    </div>

    <img src="static/assets/img/redBall.png" id="redBallImg" width="523" height="520" style="display: none;" />
    <img src="static/assets/img/blueBall.png" id="blueBallImg" width="523" height="520" style="display: none;" />
    <img src="static/assets/img/greenBall.png" id="greenBallImg" width="146" height="145" style="display: none;" />
    <img src="static/assets/img/goldBall.png" id="goldBallImg" width="146" height="145" style="display: none;" />

    
  </div>
  <script type="module" src="static/build/main.js"></script>
</body>

</html>

templates/layout.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} </title>
    <link rel="stylesheet" href="static/templates.css" />
</head>
<body class="body-del-edit-add">
    {% block content %}{% endblock %}

    {% if message %}
        <p class="message">{{ message }}</p>
    {% endif %}
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>Вхід</title>
    <link rel="stylesheet" href="static/templates.css" />
</head>
<body>
    <h2>Вхід</h2>
    <form method="POST" action="/login">
        <input type="text" name="username" placeholder="Ім'я користувача" required>
        <input type="password" name="password" placeholder="Пароль" required>
        <button type="submit">Увійти</button>
    </form>

    {% if message %}
        <p class="message">{{ message }}</p>
    {% endif %}
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
    <div>
    <a href="/register">Реєстрація</a>
    </div>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="uk">
<head>
    <meta charset="UTF-8">
    <title>Реєстрація</title>
    <link rel="stylesheet" href="static/templates.css" />
</head>
<body>
    <h2>Реєстрація</h2>
    <form method="POST" action="/register">
        <input type="text" name="username" placeholder="Ім'я користувача" required>
        <input type="password" name="password" placeholder="Пароль" required>
        <button type="submit">Зареєструватися</button>
    </form>

    {% if message %}
        <p class="message">{{ message }}</p>
    {% endif %}
    {% if error %}
        <p class="error">{{ error }}</p>
    {% endif %}
</body>
</html>

web_macro_mech/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="./favicon.png" type="image/x-icon">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="static/index.css" />
    <title>Problems List</title>
</head>

<body>
    <div class="container">
        <h1 class="mt-4">Задачі користувача <i>{{current_user.username}}</i></h1>
        <div>
            <a href="{{ url_for('main.add_prob') }}" class="btn btn-primary">Додати Задачу</a>
            <a href="{{ url_for('main.index') }}" class="btn btn-primary">На Головну</a>
            <a href="{{ url_for('auth.logout') }}" class="btn btn-primary">Вихід</a>

        </div>

        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>Назва</th>
                    <th>Умова</th>
                    <th>Відкр</th>  
                    <th>Редаг</th>  
                    <th>Видал</th>                    
                </tr>
            </thead>
            <tbody>
                {% for problem in problems %}                
                <tr>
                    <td>{{ problem.title }}</td>
                    <td>{{ problem.cond }}</td>
                    {% set color = 'green' if problem.isOpen else 'red'  %}
                    {% set yesNo = 'Так' if problem.isOpen else 'Ні'  %}
                    

                    <td>
                        <a href="{{ url_for('main.switch', id=problem.id ) }}"
                           style="color: {{ color }}">{{yesNo}}</a>
                    </td>

                    <td><a href="{{ url_for('main.edit_prob', id=problem.id ) }}">ред</a></td>
                    <td><a href="{{ url_for('main.del_prob', id=problem.id ) }}">вид</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>